#!/bin/bash
set -ex

if [ "$DOCKER_TAG" == latest ]; then
    for file in "$(ls *.Dockerfile)"; do
        docker build \
            --file "$file" \
            --tag "$DOCKER_REPO:$(basename "$file" .Dockerfile)" .
    done
fi
