name: cd

on:
  pull_request:
  push:
    branches: [master]
  workflow_dispatch:

env:
  DOCKER_BUILDKIT: 1
  PUSH: ${{ toJSON(github.ref == 'refs/heads/master') }}
  PLATFORMS: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.0

  build-push:
    runs-on: ubuntu-latest
    needs: pre-commit
    env:
      DOCKER_REPO: tecnativa/docker-duplicity
    steps:
      - uses: actions/checkout@v2
      # TODO Use YAML anchors when available
      # Get git metadata (see https://github.com/docker/build-push-action#handle-tags-and-labels)
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${{ env.DOCKER_REPO }} # list of Docker images to use as base name for tags
          tag-sha: true # add git short SHA as Docker tag
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.BOT_LOGIN }}
          password: ${{ secrets.BOT_TOKEN }}
      # Build and push stable images to DockerHub and to GHCR
      - name: Build and push :docker-s3
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ env.PLATFORMS }}
          load: ${{ !fromJSON(env.PUSH) }}
          push: ${{ fromJSON(env.PUSH) }}
          tags: |
            ghcr.io/${{ env.DOCKER_REPO }}:docker-s3
            ${{ env.DOCKER_REPO }}:docker-s3
          target: docker-s3
          labels: ${{ steps.docker_meta.outputs.labels }}
      - name: Build and push :postgres-s3
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ env.PLATFORMS }}
          load: ${{ !fromJSON(env.PUSH) }}
          push: ${{ fromJSON(env.PUSH) }}
          tags: |
            ghcr.io/${{ env.DOCKER_REPO }}:postgres-s3
            ${{ env.DOCKER_REPO }}:postgres-s3
          target: postgres-s3
          labels: ${{ steps.docker_meta.outputs.labels }}
      - name: Build and push :docker
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ env.PLATFORMS }}
          load: ${{ !fromJSON(env.PUSH) }}
          push: ${{ fromJSON(env.PUSH) }}
          tags: |
            ghcr.io/${{ env.DOCKER_REPO }}:docker
            ${{ env.DOCKER_REPO }}:docker
          target: docker
          labels: ${{ steps.docker_meta.outputs.labels }}
      - name: Build and push :postgres
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ env.PLATFORMS }}
          load: ${{ !fromJSON(env.PUSH) }}
          push: ${{ fromJSON(env.PUSH) }}
          tags: |
            ghcr.io/${{ env.DOCKER_REPO }}:postgres
            ${{ env.DOCKER_REPO }}:postgres
          target: postgres
          labels: ${{ steps.docker_meta.outputs.labels }}
      - name: Build and push :latest
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ env.PLATFORMS }}
          load: ${{ !fromJSON(env.PUSH) }}
          push: ${{ fromJSON(env.PUSH) }}
          tags: |
            ghcr.io/${{ env.DOCKER_REPO }}:latest
            ${{ env.DOCKER_REPO }}:latest
          target: latest
          labels: ${{ steps.docker_meta.outputs.labels }}
